name: Create release from tag

on:
  push:
    tags:
      - '*'

jobs:
  createreleasefropmtag:
    name: Create release from tag
    # Only run cron on innoweb accounts
    if: github.repository_owner == 'xini' || github.repository_owner == 'innowebau'
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Essential for authentication
        run: gh release create "$GITHUB_REF_NAME" --generate-notes
